Update php_linter.yml (#56)
Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/php_linter.yml b/.github/workflows/php_linter.yml
--- a/.github/workflows/php_linter.yml
+++ b/.github/workflows/php_linter.yml
@@ -11,7 +11,7 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
-        token: ${{ secrets.GITHUB_TOKEN }}
+        token: ${{ secrets.PHPLINT_TOKEN }}
 
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
@@ -41,6 +41,17 @@ jobs:
     
     - name: Run PHP_CodeSniffer
       run: |
-        phpcs --standard=PSR2 . --ignore=vendor/* || echo "Still errors, fix these mmanually"
+        if [[ "${{ steps.create-pr.outputs.pull-request-number }}" != "" ]]; then
+          echo "A PR was created. Marking this step as failed."
+          exit 1
+        fi
+        if phpcs --standard=PSR2 . --ignore=vendor/* --warning-severity=0; then
+          echo "No coding standards errors found."
+        else
+          echo "Coding standards errors detected."
+          exit 1
+        fi
+
+
 
     
